<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTZDdk5X\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTZDdk5X/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTZDdk5X.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTZDdk5X\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTZDdk5X\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TZDdk5X',
    'container.build_id' => '5a714f17',
    'container.build_time' => 1620731804,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTZDdk5X');
